# Generated by Django 3.0.2 on 2020-06-21 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.CharField(max_length=10)),
                ('employeeName', models.CharField(max_length=30)),
                ('timeZone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_Time', models.DateTimeField()),
                ('End_Time', models.DateTimeField()),
                ('EmployeeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='employee.Employee')),
            ],
        ),
    ]
